# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Tech~Pulse
dynamic_title: "TechPulse"
email: techpulse@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Stay ahead with the latest trends, innovations, and insights
    in the world of technology.
baseurl: "/techpulse" # the subpath of your site, e.g. /blog
url: "https://hvenkatraman.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: hvenkatraman9
github_username:  hvenkatraman

# Build settings
theme: minima
plugins:
  - jekyll-feed
minima:
  skin: none  # Disable default Minima skin
  skin_mode: false  # Disable mode switching if present

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#
social:
  - name: Facebook
    url: https://facebook.com/yourprofile
    icon: facebook-icon.png

  - name: Twitter
    url: https://twitter.com/yourprofile
    icon: twitter-icon.png

  - name: Instagram
    url: https://instagram.com/yourinstaprofile
    icon: instagram-icon.png

  - name: GitHub
    url: https://github.com/yourgithubprofile
    icon: github-icon.png

  - name: WhatsApp
    url: https://wa.me/yourwhatsapplink
    icon: whatsapp-icon.png

  - name: LinkedIn
    url: https://linkedin.com/in/yourlinkedinprofile
    icon: linkedin-icon.png
header_pages:
  - index.md
  - about.md
  - blog.md
  - contact.md
  - root.md
  - tech-posts-list.md

nav:
  - title: Home
    url: /
  - title: Blog
    url: /blog/
  - title: About
    url: /about/
  - title: Contact
    url: /contact/
